# Generated by Django 3.1.6 on 2021-02-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoke', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='speaker_info',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
